export const SELECT_CUSTOMER = 'SELECT_CUSTOMER'
export const SELECT_CONTACT = 'SELECT_CONTACT'
export const SAVE_ORDER_DATA = 'SAVE_ORDER_DATA'
export const CLEAR_ORDER_DATA = 'CLEAR_ORDER_DATA'
export const SAVE_ALL_ORDERS_TAB_INDEX = 'SAVE_ALL_ORDERS_TAB_INDEX' // 我的订单列表
export const SAVE_DISPATCH_ORDERS_TAB_INDEX = 'SAVE_DISPATCH_ORDERS_TAB_INDEX' // 我要派单列表
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
